name: Update Opportunity Map

on:
  schedule:
    # Every day at 12:00 UTC
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write    # needed to commit back to the repo
  actions: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TICKETMASTER_API_KEY: ${{ secrets.TICKETMASTER_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # Fallbacks if requirements.txt isn't present
            pip install folium requests pandas python-dateutil
          fi

      - name: Build map HTML
        shell: bash
        run: |
          set -euo pipefail
          echo "Using Python $(python --version)"
          # Try common entry points; adjust if your repo uses a specific script.
          if [ -f update_map.py ]; then
            python update_map.py
          elif [ -f scripts/update_map.py ]; then
            python scripts/update_map.py
          elif [ -f tools/update_map.py ]; then
            python tools/update_map.py
          else
            echo "ERROR: Could not find update_map.py (tried ./, scripts/, tools/)."
            exit 1
          fi

          # Ensure the expected output path exists
          if [ ! -f docs/fever_market_opportunity_map.html ]; then
            echo "ERROR: docs/fever_market_opportunity_map.html was not created."
            exit 1
          fi

      - name: Commit changes (if any)
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add docs/fever_market_opportunity_map.html
            git commit -m "chore: auto-update map (GitHub Actions)"
            git push
          else
            echo "No changes to commit."
          fi
