name: Update Fever Opportunity Map

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 12 * * *"  # daily at 12:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TM_API_KEY: ${{ secrets.TM_API_KEY }}
      # ---- Recommended knobs (edit as you like) ----
      TM_SEGMENT: "Music"
      TM_COUNTRIES: "US,CA"
      TM_PAGES_MAX: "3"
      TM_PAGE_SIZE: "200"
      # Color scaling (so the map isn't all blue)
      COLOR_PCT_LOW: "25"
      COLOR_PCT_HIGH: "90"
      # Google Trends (CI-friendly)
      TRENDS_MODE: "country"           # 'country' or 'off'
      TRENDS_SLEEP_MS: "400"           # throttle between calls
      TRENDS_TERMS: "live music,concerts"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install requests tenacity folium branca pandas numpy python-dateutil pytrends

      - name: Debug - verify paths
        run: |
          echo "WORKSPACE=${GITHUB_WORKSPACE}"
          ls -la
          echo "--- scripts ---"
          ls -la scripts || true
          echo "--- docs ---"
          ls -la docs || true

      - name: Build map (pure Python)
        run: |
          set -euo pipefail
          test -f scripts/build_map.py || (echo "scripts/build_map.py missing" && exit 1)
          python scripts/build_map.py

      - name: Ensure .nojekyll
        run: touch docs/.nojekyll

      - name: Commit and push updated artifacts
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/fever_market_opportunity_map.html docs/fever_events.geojson docs/trends_debug.csv docs/.nojekyll || true
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update map (pure Python)"
            git push
          else
            echo "No changes to commit."
          fi
